algoritmo "Caixa Eletronico"
// Aula 05 - Exercicio 10 - Estrutura ENQUANTO
// Solicita a senha enquanto ela for diferente de 2026.
var
   senha: inteiro
inicio
   escreva("Digite a sua senha: ")
   leia(senha)

   enquanto (senha <> 2026) faca
      escreval("Senha incorreta! Tente novamente.")
      escreva("Digite a sua senha: ")
      leia(senha)
   fimenquanto

   escreval("Acesso liberado!")
fimalgoritmo
